title: Lorerim
description: A wiki for documentation, tips and guides on the Lorerim modlist
theme: just-the-docs
color_scheme: lorerim
logo: "/assets/logos/logo.png"
favicon_ico: "/assets/logos/LorerimIcon.ico"
url: "https://lorerim.com"
baseurl: "" # Leave empty since it's at the root

aux_links:
  Discord: https://discord.gg/bungalo
  Wabbajack: https://www.wabbajack.org
  Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/112590

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Gouldsonium"

collections:
  support:
    permalink: "/:collection/:path/"
    output: true

  guides:
    permalink: "/:collection/:path/"
    output: true

  other:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    support:
      name: Support
      nav_fold: false

    guides:
      name: Guides
      nav_fold: true

    other:
      name: Other
      nav_fold: true
